<script src="/assets/xheditor/xheditor-1.1.14-zh-cn.min.js"></script>
<script type="text/javascript">
<!--

//-->
</script>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('Archives', array('action' => 'create')));
$form->prepare();

echo $this->form()->openTag($form) . PHP_EOL;
echo $this->formHidden($form->get('id')) . PHP_EOL;
echo $this->formRow($form->get('title')) . PHP_EOL;
echo $this->formRow($form->get('content')) . PHP_EOL;
echo $this->formInput($form->get('submit')) . PHP_EOL;
echo $this->form()->closeTag($form) . PHP_EOL;

