<?php
echo "确认删除 ：{$this->escapehtml($row->title)}<br />" . htmlspecialchars_decode(stripcslashes($row->content));
$url = $this->url('Archives', array(
    'action' => 'delete',
    'id' => $this->id
));
echo "<form action=\"{$url}\" method=\"post\">";
echo "<input type=\"hidden\" name=\"id\" value=\"{$row->id}\" />";
echo "<input type=\"submit\" name=\"del\" value=\"Yes\" />    ";
echo "<input type=\"submit\" name=\"del\" value=\"No\">";
echo "</form>";