<script src="/assets/xheditor/xheditor-1.1.14-zh-cn.min.js"></script>
<?php 
$form=$this->form;
$form->setAttribute('action',$this->url('Archives',array('action'=>'edit','id'=>$this->id)));
$form->prepare();
echo $this->form()->openTag($form).PHP_EOL;
echo $this->formhidden($form->get('id')).PHP_EOL;
echo $this->formrow($form->get('title')).PHP_EOL;
echo $this->formrow($form->get('content')).PHP_EOL;
echo $this->forminput($form->get('submit')).PHP_EOL;
echo $this->form()->closeTag($form).PHP_EOL;