<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Insert title here</title>
</head>
<body>
<a href="<?php echo $this->url('Archives',array('action'=>'create'));?>">添加</a><br />
<?php 
foreach ($this->rows as $val) {
	echo 'ID:'.$this->escapehtml($val->id);
	echo '   Title:'.$this->escapehtml($val->title)." <a href=\"{$this->url('Archives',array('action'=>'edit','id'=>$val->id))}\">编辑</a>  <a href=\"{$this->url('Archives',array('action'=>'delete','id'=>$val->id))}\">删除</a><br>";
}
echo $this->paginationControl($this->rows, 'Sliding', 'pagination/paginator.phtml');
?>
</body>
</html>