<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<title>Simpla Admin</title>
<!--                       CSS                       -->
<!-- Reset Stylesheet -->
<link rel="stylesheet" href="/assets/resources/css/reset.css" type="text/css" media="screen">
<!-- Main Stylesheet -->
<link rel="stylesheet" href="/assets/resources/css/style.css" type="text/css" media="screen">
<!-- Invalid Stylesheet. This makes stuff look pretty. Remove it if you want the CSS completely valid -->
<link rel="stylesheet" href="/assets/resources/css/invalid.css" type="text/css" media="screen">
</head>
<body>
<div id="body-wrapper"> 
  <!-- Wrapper for the radial gradient background -->
  <div id="sidebar">
    <div id="sidebar-wrapper"> 
      <!-- Sidebar with logo and menu -->
      <h1 id="sidebar-title"><a href="#">Simpla Admin</a></h1>
      <!-- Logo (221px wide) --> 
      <a href="#"><img id="logo" src="/assets/resources/images/logo.png" alt="Simpla Admin logo"></a> 
      <!-- Sidebar Profile links -->
      <div id="profile-links"> Hello, <a href="#" title="Edit your profile">865171</a>, you have <a href="#messages" rel="modal" title="3 Messages">3 Messages</a><br>
        <br>
        <a href="#" title="View the Site">View the Site</a> | <a href="#" title="Sign Out">Sign Out</a> </div>
      <ul id="main-nav">
        <!-- Accordion Menu -->
        <li> <a href="#" class="nav-top-item no-submenu"> 
          <!-- Add the class "no-submenu" to menu items with no sub menu --> 
          Dashboard </a> </li>
        <li> <a href="#" class="nav-top-item current"> 
          <!-- Add the class "current" to current menu item --> 
          Articles </a>
          <ul style="display: block;">
            <li><a href="#">Write a new Article</a></li>
            <li><a class="current" href="#">Manage Articles</a></li>
            <!-- Add class "current" to sub menu items also -->
            <li><a href="#">Manage Comments</a></li>
            <li><a href="#">Manage Categories</a></li>
          </ul>
        </li>
        <li> <a href="#" class="nav-top-item"> Pages </a>
          <ul style="display: none;">
            <li><a href="#">Create a new Page</a></li>
            <li><a href="#">Manage Pages</a></li>
          </ul>
        </li>
        <li> <a href="#" class="nav-top-item"> Image Gallery </a>
          <ul style="display: none;">
            <li><a href="#">Upload Images</a></li>
            <li><a href="#">Manage Galleries</a></li>
            <li><a href="#">Manage Albums</a></li>
            <li><a href="#">Gallery Settings</a></li>
          </ul>
        </li>
        <li> <a href="#" class="nav-top-item"> Events Calendar </a>
          <ul style="display: none;">
            <li><a href="#">Calendar Overview</a></li>
            <li><a href="#">Add a new Event</a></li>
            <li><a href="#">Calendar Settings</a></li>
          </ul>
        </li>
        <li> <a href="#" class="nav-top-item"> Settings </a>
          <ul style="display: none;">
            <li><a href="#">General</a></li>
            <li><a href="#">Design</a></li>
            <li><a href="#">Your Profile</a></li>
            <li><a href="#">Users and Permissions</a></li>
          </ul>
        </li>
      </ul>
      <!-- End #main-nav --> 
    </div>
  </div>
  <!-- End #sidebar --> 
  <div id="main-content">
  <?php echo $this->content;?>
  <!-- End Notifications -->
    <div id="footer"> <small>
      <!-- Remove this notice or replace it with whatever you want -->
      &copy; Copyright 2010 Your Company | Powered by <a href="http://www.865171.cn">admin templates</a> | <a href="#">Top</a> </small> </div>
    <!-- End #footer -->
  </div>
  
  <!-- End #main-content --> 
</div>
<!-- Download From www.exet.tk-->
<!--                       Javascripts                       -->
<!-- jQuery -->
<script type="text/javascript" src="/assets/resources/scripts/jquery-1.3.2.min.js"></script>
<!-- jQuery Configuration -->
<script type="text/javascript" src="/assets/resources/scripts/simpla.jquery.configuration.js"></script>
<!-- Facebox jQuery Plugin -->
<script type="text/javascript" src="/assets/resources/scripts/facebox.js"></script>
<!-- jQuery WYSIWYG Plugin -->
<script type="text/javascript" src="/assets/resources/scripts/jquery.wysiwyg.js"></script>
<!-- jQuery Datepicker Plugin -->
<script type="text/javascript" src="/assets/resources/scripts/jquery.datePicker.js"></script>
<script type="text/javascript" src="/assets/resources/scripts/jquery.date.js"></script>
</body>
</html>