<div class="header">
	<h1 class="page-title">门店列表</h1>
</div>

<ul class="breadcrumb">
	<li><a href="/home">首页</a> <span class="divider">/</span></li>
	<li class="active">门店列表</li>
</ul>

<div class="container-fluid">
	<div class="row-fluid">
        <?php 
    	if ($this->success)
    	{
    		echo "<div class=\"alert alert-success\">
            <a class=\"close\" data-dismiss=\"alert\">×</a>
            <strong>{$this->success->title}</strong>  {$this->success->message}</div>";
    	}
    	if (($this->userData['shopCount'] > $this->count || $this->userData['shopCount']==0) && empty($this->action)){
    	?>
		<div class="btn-toolbar">
				<a href="/shop/create" class="btn btn-primary"><i class="icon-plus"></i> 添加门店</a>
			<!-- <button class="btn">Import</button>
			<button class="btn">Export</button> -->
			<div class="btn-group"></div>
		</div>
		<?php 
		}
		if ($this->action=='m')
		{
			echo "<form  name=\"editM\" method=\"post\" action=\"\">";
		    echo "<div class=\"btn-toolbar\"><button class=\"btn\">提交</button><div class=\"btn-group\"></div></div>";
		}
		?>
		<div class="well">
			<table class="table">
				<thead>
					<tr>
						<th width="6%">#</th>
						<th>名称</th>
						<th>电话</th>
						<th>地址</th>
						<th style="width: 50px;">改/删</th>
					</tr>
				</thead>
				<tbody>
				<?php 
				if ($this->rows)
				{
					foreach ($this->rows as $val) {
				?>
					<tr id="shop_<?php echo $val['id'];?>">
						<td><?php 
						if ($this->action=='m')
						{
							echo "<input type=\"checkbox\" name=\"id[]\" id=\"id\" value=\"{$val['id']}\"";
							if (in_array($val['id'], $this->userShop)) echo ' checked="checked"';
							echo " />";
						}else 
						{
							echo $val['id'];
						}
						?></td>
						<td><?php echo $val['thumb']?' <a href="'.$val['thumb'].'" title="预览标题图片" target=_blank><img src="/images/showimg.gif" border=0></a>':'  <font color="red">无图</font>'?><?php echo $val['shopname'];?></td>
						<td><?php echo $val['tel'];?></td>
						<td><?php echo $val['address'];?></td>
						<td>
						<a href="/shop/edit?id=<?php echo $val['id']?>" title="修改"><i class="icon-pencil"></i></a> &nbsp;
						<a href="#myModal" title="删除" role="button" data-toggle="modal" onclick="remove(<?php echo $val['id'];?>);"><i class="icon-remove"></i></a>
						</td>
					</tr>
					<?php 
					  }
			   }
					?>
				</tbody>
			</table>
		</div>
		<?php 
		  echo $this->action=='m'?'</form>':'';
		  echo $this->paginationControl($this->rows, 'Sliding', 'pagination/pagination.phtml',array('action'=>$this->action,'id'=>$this->id));
        ?>
        <script type="text/javascript">
           function remove(i){
                 $('#remove').attr('onclick','removeShop('+ i +')');
               }
             function removeShop(i)
             {
                 $.post('/shop/delete?id='+i,{'id':i},function(data){
                     if (data.isok==true)
                     {
                    	 $('#shop_'+i).hide();
                     }
                 },'json');
             }
		   </script>
		<div class="modal small hide fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
				<h3 id="myModalLabel">删除门店</h3>
			</div>
			<div class="modal-body">
				<p class="error-text">
					<i class="icon-warning-sign modal-icon"></i>确认删除当前选定的门店？
				</p>
			</div>
			<div class="modal-footer">
				<button class="btn" data-dismiss="modal" aria-hidden="true">取消</button>
				<button class="btn btn-danger" id="remove" data-dismiss="modal">确认</button>
			</div>
		</div>
		<?php echo $this->partial('partials/homeFooter.phtml');?>
	</div>
</div>