<div class="header">
	<h1 class="page-title">编辑商品</h1>
</div>

<ul class="breadcrumb">
	<li><a href="/home">首页</a> <span class="divider">/</span></li>
	<li><a href="/commodity">商品列表</a> <span class="divider">/</span></li>
	<li class="active">编辑商品</li>
</ul>

<div class="container-fluid">
	<div class="row-fluid">
<form id="tab" name="commodityCreate" method="post" onsubmit="return clickForm();" action="?id=<?php echo $this->row['id'];?>" enctype="multipart/form-data">
		<div class="btn-toolbar">
		    <input type="submit" name="submit" id="submit"  class="btn btn-primary" value="提交" />
			<div class="btn-group"></div>
		</div>
		<div class="well">
			<ul class="nav nav-tabs">
				<li class="active"><a href="#home" data-toggle="tab">基础配置</a></li>
				<li><a href="#profile" data-toggle="tab">描述内容</a></li>
			</ul>
			<div id="myTabContent" class="tab-content">
          <div class="tab-pane active in" id="home">
            <div class="control-group" id="group-shop">
              <label class="control-label" for="shop">门店名称</label>
              <div class="controls">
                <select name="shop" id="shop">
                <option value="">请选择门店</option>
                  <?php 
						if ($this->shop)
						{
							foreach ($this->shop as $val) {
								echo "<option value=\"{$val['id']}\"";
								if ($this->row['shop']==$val['id']) echo ' selected="true"';
								echo ">{$val['shopname']}</option>";
							}
						}
						?>
                </select>
                <span class="help-inline" id="help-shop"></span> </div>
            </div>
            <div class="control-group" id="group-cateID">
              <label class="control-label" for="cateID">商品分类</label>
              <div class="controls">
                <select name="cateID" id="cateID">
                <option value="">请选择分类</option>
                  <?php 
						if ($this->type)
						{
							foreach ($this->type as $val) {
								echo "<option value=\"{$val['id']}\"";
								if ($this->row['cateID']==$val['id']) echo ' selected="true"';
								echo ">{$val['name']}</option>";
							}
						}
						?>
                </select>
                <span class="help-inline" id="help-cateID"></span> </div>
            </div>
            <div class="control-group" id="group-fileField">
              <label class="control-label" for="fileField">缩略图</label>
              <div class="controls">
                <input type="file" class="input-file" name="fileField" id="fileField" />
                <span class="help-inline" id="help-fileField"></span> 
                </div>
            </div>
            <div class="control-group" id="group-wares">
              <label class="control-label" for="wares">商品名称</label>
              <div class="controls">
                <input type="text" value="<?php echo $this->row['name'];?>" name="wares" id="wares" class="span3">
                <span class="help-inline" id="help-wares"></span> </div>
            </div>
            <div class="control-group" id="group-price">
              <label class="control-label" for="price">价格</label>
              <div class="controls">
                <input type="text" value="<?php echo $this->row['price'];?>" name="price" id="price" class="span3">
                <span class="help-inline" id="help-price"></span> </div>
            </div>
            <div class="control-group" id="group-rebate">
              <label class="control-label" for="rebate">折扣价</label>
              <div class="controls">
                <input type="text" value="<?php echo $this->row['rebate'];?>" name="rebate" id="rebate" class="span3">
                <span class="help-inline" id="help-rebate"></span> </div>
            </div>
            <div class="control-group" id="group-order">
              <label class="control-label" for="order">排序</label>
              <div class="controls">
                <input type="text" value="<?php echo $this->row['order'];?>" name="order" class="span3" onkeyup="value=value.replace(/[^\d]/g,'')">
                <span class="help-inline" id="help-order"></span> </div>
            </div>
            <div class="control-group" id="group-repertory">
              <label class="control-label" for="repertory">库存量</label>
              <div class="controls">
                <input type="text" value="<?php echo $this->row['repertory'];?>" name="repertory" id="repertory" class="span3" onkeyup="value=value.replace(/[^\d]/g,'')">
                <span class="help-inline" id="help-repertory"></span> </div>
            </div>
            <div class="control-group" id="group-sold">
              <label class="control-label" for="sold">售出数量</label>
              <div class="controls">
                <input type="text" value="<?php echo $this->row['sold'];?>" name="sold" class="span3" onkeyup="value=value.replace(/[^\d]/g,'')">
                <span class="help-inline" id="help-sold"></span> </div>
            </div>
            <div class="control-group" id="group-fileField">
              <label class="control-label" for="fileField">产品图片</label>
              <div class="controls">
                <input type="file" name="upload" id="upload" />
                <span id="uploads"></span> <span class="help-inline" id="help-sold"></span> 
                
                </div>
            </div>
            <div class="control-group" id="group-added">
              <label class="control-label" for="added">是否上架</label>
              <div class="controls"> 是
                <input type="radio" value="1" name="added"  <?php echo $this->row['added']==1?'checked':'';?> >
                否
                <input type="radio" value="0" name="added"  <?php echo $this->row['added']==0?'checked':'';?>>
              </div>
            </div>
            <div class="control-group" id="group-commend">
              <label class="control-label" for="commend">是否上架</label>
              <div class="controls"> 是
                <input type="radio" value="1" name="commend" <?php echo $this->row['commend']==1?'checked':'';?>>
                否
                <input type="radio" value="0" name="commend" <?php echo $this->row['commend']==0?'checked':'';?>>
              </div>
            </div>
          </div>
          <div class="tab-pane fade" id="profile">
            <div class="control-group" id="group-weixin">
              <label class="control-label" for="weixin">微信描述</label>
              <div class="controls">
                <textarea rows="4" class="span8" id="weixin" name="weixin"><?php echo nl2br($this->row['weixin']);?></textarea>
                <span class="help-inline" id="help-weixin"></span> </div>
            </div>
            <div class="control-group" id="group-content">
              <label class="control-label" for="content">产品描述</label>
              <div class="controls">
                <textarea rows="4" class="span8" id="content" name="content"><?php echo htmlspecialchars_decode(stripcslashes($this->row['content']));?></textarea>
                <span class="help-inline" id="help-content"></span> </div>
            </div>
          </div>
        </div>
		</div>
		 <script type="text/javascript">
		<?php $timestamp = time();?>
           $(function() {
           $('#upload').uploadify({
           'buttonText' : '选择文件',
           'fileSizeLimit' : '2048KB',
           'fileTypeDesc' : 'Image Files',
           'fileTypeExts' : '*.gif; *.jpg; *.png',
           'fileObjName' : 'fileField',
           'method'   : 'post',
                				'formData'     : {
                					'timestamp' : '<?php echo $timestamp;?>',
                					'token'     : '<?php echo md5('unique_salt' . $timestamp);?>',
                				},
                				'swf'      : '/lib/uploadify/uploadify.swf',
                				'uploader' : '/uploadify.php',
                				'onUploadSuccess':function(file,data,response){
                                    if (response && data!="error")
                                        {
                                            $('#uploads').append('<input type="hidden" name="images[]" value="'+data+'">');
                                        }
                    				}
                			});
         });
     </script> 
		<?php echo $this->partial('partials/homeFooter.phtml')?>
</form>
	</div>
</div>
<script src="/ueditor/ueditor.all.min.js"></script>
<script src="/ueditor/ueditor.config.js"></script>