<div class="header">
	<h1 class="page-title">商品列表</h1>
</div>
<ul class="breadcrumb">
	<li><a href="/home">首页</a> <span class="divider">/</span></li>
	<li class="active">欢迎推荐</li>（推荐的商品，在用户关注您的账号之后接收到的商品列表，建议不超过10个。）
</ul>
<div class="container-fluid">
	<div class="row-fluid">
	<?php 
	if ($this->success)
	{
		echo "<div class=\"alert alert-success\">
		<a class=\"close\" data-dismiss=\"alert\">×</a>
		<strong>{$this->success->title}</strong>  {$this->success->message}</div>";
	}
	?>
       <form name="commodityC" method="post"  >
        	     <div class="btn-toolbar">
		         <?php 
		          if (count($this->rows)) echo '<button class="btn">取消推荐</button>';
		         ?>
		         <a href="/commodity?action=c" class="btn btn-primary"><i class="icon-plus"></i> 添加推荐商品</a>
			     <div class="btn-group"></div></div>
		
		<div class="well">
			<table class="table">
				<thead>
					<tr>
						<th width="3%">#</th>
						<th>商品名称</th>
						<th width="10%">门店</th>
						<th width="10%">分类</th>
						<th width="11%">价格/折扣价</th>
						<th width="5%">库存</th>
						<th width="5%">售出</th>
						<th width="8%">上架</th>
						<th width="8%">推荐</th>
						<th style="width: 50px;">改/删</th>
					</tr>
				</thead>
				<tbody>
				<?php 
				if ($this->rows)
				{
					foreach ($this->rows as $val) {
				?>
					<tr id="commodity_<?php echo $val['id'];?>">
						<td><?php echo "<input type=\"checkbox\" name=\"id[]\" id=\"id\" value=\"{$val['id']}\"";?></td>
						<td><?php echo $val['thumb']?' <a href="'.$val['thumb'].'" title="预览标题图片" target=_blank><img src="/images/showimg.gif" border=0></a>':'  <font color="red">无图</font>'?><?php echo $val['name'];?></td>
						<td><?php echo isset($this->shop[$val['shop']])?$this->shop[$val['shop']]:'未知门店';?></td>
						<td><?php echo isset($this->type[$val['cateID']])?$this->type[$val['cateID']]:'未知分类';?></td>
						<td><?php echo $val['price'].'/'.$val['rebate'];?></td>
						<td><?php echo $val['repertory'];?></td>
						<td><?php echo $val['sold'];?></td>
						<td><?php echo $val['added']==1?'已上架':'未上架';?></td>
						<td><?php echo $val['commend']==1?'已推荐':'未推荐'?></td>
						<td>
						<a href="/commodity/edit?id=<?php echo $val['id'];?>" title="修改"><i class="icon-pencil"></i></a>&nbsp;
						<a href="#myModal" role="button" data-toggle="modal" onclick="remove(<?php echo $val['id'];?>);" title="删除"><i class="icon-remove"></i></a>
						</td>
					</tr>
					<?php 
					}
					}
					?>
				</tbody>
			</table>
		</div>
		</form>
		<?php 
		echo $this->partial('partials/homeFooter.phtml');
		?>
	</div>
</div>