<div class="header">
	<h1 class="page-title">图片消息列表</h1>
</div>
<ul class="breadcrumb">
	<li><a href="/home">首页</a> <span class="divider">/</span></li>
	<li class="active">图片消息列表</li>
</ul>

<div class="container-fluid">
	<div class="row-fluid">
		<div class="btn-toolbar">
		</div>
		<div class="well">
			<table class="table">
				<thead>
					<tr>
						<th width="5%">#</th>
						<th width="50%">图片</th>
						<th width="20%">提交时间</th>
						<th width="20%">消息ID</th>
						
					</tr>
				</thead>
				<tbody>
				<?php 
				if ($this->rows)
				{
				    foreach ($this->rows as $val) {
				?>
					<tr>
					    <td ><?php echo $val['id'];?></td>
						<td ><a href="" target="_b"><img src="<?php echo $val['url'];?>" width="48" height="48"></a></td>
						<td><?php echo date("Y-m-d",$val['createTime']);?></td>
						<td><?php echo $val['msgId'];?></td>
					</tr>
				<?php
				  } 
				}
				?>	
				</tbody>
			</table>
		</div>
		<?php
         echo $this->paginationControl($this->rows, 'Sliding', 'pagination/pagination.phtml');
         ?>
		<div class="modal small hide fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		   <script type="text/javascript">
           function reid(i){
                 $('#delid').attr('onclick','deluser('+ i +')');
               }
             function deluser(i)
             {
                 $.post('/users/delete?id='+i,{'id':i},function(data){
                     if (data.isok==true)
                     {
                    	 $('#user_'+i).hide();
                     }
                 },'json');
             }
		   </script>
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal"
					aria-hidden="true">×</button>
				<h3 id="myModalLabel">删除账号</h3>
			</div>
			<div class="modal-body">
				<p class="error-text">
					<i class="icon-warning-sign modal-icon"></i>确定删除指定的账号？
				</p>
			</div>
			<div class="modal-footer">
				<button class="btn" data-dismiss="modal" aria-hidden="true">取消</button>
				<button class="btn btn-danger" id="delid" data-dismiss="modal" >确认</button>
			</div>
		</div>
		<?php echo $this->partial('partials/homeFooter.phtml');?>
	</div>
</div>