<div class="header">
	<h1 class="page-title">链接消息列表</h1>
</div>
<ul class="breadcrumb">
	<li><a href="/home">首页</a> <span class="divider">/</span></li>
	<li class="active">链接消息列表</li>
</ul>

<div class="container-fluid">
	<div class="row-fluid">
		<div class="btn-toolbar">
		</div>
		<div class="well">
			<table class="table">
				<thead>
					<tr>
						<th width="5%">#</th>
						<th width="19%">消息标题</th>
						<th width="20%">消息描述</th>
						<th width="20%">消息链接</th>
						<th width="20%">提交时间</th>
						<th width="16%">消息ID</th>
					</tr>
				</thead>
				<tbody>
				<?php 
				if ($this->rows)
				{
				    foreach ($this->rows as $val) {
				?>
					<tr>
						<td><?php echo $val['id'];?></td>
						<td><?php echo $val['title'];?></td>
						<td><?php echo $val['description'];?></td>
						<td><a href="<?php echo $val['url'];?>" target="_blank"><?php echo $val['url'];?></a></td>
						<td><?php echo date("Y-m-d",$val['createTime']);?></td>
						<td><?php echo $val['msgId'];?></td>
					</tr>
				<?php
				  } 
				}
				?>	
				</tbody>
			</table>
		</div>
		<?php
         echo $this->paginationControl($this->rows, 'Sliding', 'pagination/pagination.phtml');
         ?>
		<?php echo $this->partial('partials/homeFooter.phtml');?>
	</div>
</div>