<div class="header">
	<h1 class="page-title">地理位置消息列表</h1>
</div>
<ul class="breadcrumb">
	<li><a href="/home">首页</a> <span class="divider">/</span></li>
	<li class="active">地理位置消息列表</li>
</ul>
<div class="container-fluid">
	<div class="row-fluid">
		<div class="btn-toolbar">
		</div>
		<div class="well">
			<table class="table">
				<thead>
					<tr>
						<th width="5%">#</th>
						<th>纬度</th>
						<th>经度</th>
						<th>缩放大小</th>
						<th>位置信息</th>
						<th>提交时间</th>
						<th>消息ID</th>
					</tr>
				</thead>
				<tbody>
				<?php 
				if ($this->rows)
				{
				    foreach ($this->rows as $val) {
				?>
					<tr>
					    <td><?php echo $val['id'];?></td>
						<td><?php echo $val['locationX'];?></td>
						<td><?php echo $val['locationY'];?></td>
						<td><?php echo $val['scale'];?></td>
						<td><?php echo $val['label'];?></td>
						<td><?php echo date("Y-m-d",$val['createTime']);?></td>
						<td><?php echo $val['msgId'];?></td>
					</tr>
				<?php
				  } 
				}
				?>	
				</tbody>
			</table>
		</div>
		<?php
         echo $this->paginationControl($this->rows, 'Sliding', 'pagination/pagination.phtml');
         ?>
		<?php echo $this->partial('partials/homeFooter.phtml');?>
	</div>
</div>