<!DOCTYPE HTML>
<html lang="zh-CN">
<head>
	<meta charset="utf-8" />
	<title><?php echo $this->row['name'];?> - 订购页</title>
	<meta name="version" content="游太网络" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0;" />
	<meta name="format-detection" content="telephone=no" />
	<link type="text/css" rel="stylesheet" href="/css/style.css" />
	<script type="text/javascript" src="/js/jquery.min.js"></script>
	<script type="text/javascript" src="/js/main.js"></script>
</head>

<body>
	<?php echo $this->partial ( 'partials/header.phtml',array('openid'=>$this->openid));?>
	<!--主体-->
<div class="main">
    <form action="?openid=<?php echo $this->openid;?>&id=<?php echo $this->row['id'];?>" method="post" onsubmit="return checkform()">
    	<div class="p_mod">
    		<h2 class="p_mod_title">订单信息</h2>
    		<ul>
    			<li><strong>名称：</strong><font><?php echo $this->row['name'];?></font></li>
    			<li><strong>单价：</strong><font>￥<?php echo $this->row['rebate'];?> <del>￥<?php echo $this->row['price'];?></del></font></li>
    			<li><strong>数量：</strong>
    				<div class="o_num_input clearfix">
                        <input type="hidden" class="product_nums"  value="<?php echo $this->row['repertory'];?>" />
                        <input type="hidden" class="product_price" value="<?php echo $this->row['rebate'];?>" />
    					<a class="minus ts2" href="javascript:undefined">-</a>
    		            <input type="input" readonly="true" name="num" class="num" value="1"/>
    		            <a class="plus ts2 on" href="javascript:undefined">+</a>
    				</div>
    			</li>
    			<!--<li><strong>运费：</strong><font>￥8</font></li>-->
    			<li><strong>总价：</strong><font class="org total_fee">￥<?php echo $this->row['rebate'];?></font></li>
    		</ul>
    	</div>
    	<div class="p_mod">
    		<h2 class="p_mod_title">收货信息  [ <a href="/user/address?openid=<?php echo $this->openid;?>&id=<?php echo $this->row['id'];?>">添加</a> ]</h2>
    		
    		<ul id="address_list">
    		
    		<?php
    		$default='';
    		if ($this->rows)
    		{
    			foreach ($this->rows as $val) {
                if ($val['default']) $default=$val['id'];
    		?>
            <li>
               <a href="javascript:void(0);" id="aid_<?php echo $val['id'];?>" onclick="selectAddress(<?php echo $val['id'];?>);" <?php echo $val['default']==1?'class="focus"':'';?> >
               <?php echo $val['name'];?>  <?php echo $val['phone'];?> <?php echo $val['province'];?> <?php echo $val['city'];?>  <?php echo $val['address'];?> <?php echo $val['zipcode'];?> 
               <span></span>
               </a>
            </li>
            <?php 
               }
            }
            echo "<input type=\"hidden\" name=\"address\" id=\"address_id\" value=\"{$default}\" >";
            ?>
            </ul>
    	</div>
        
    	<!--  div class="p_mod o_list">
    		<h2 class="p_mod_title">配送时间</h2>
    		<ul>
    			<li><a class="focus" href="javascript:">只工作日配送（周一到周五）<span></span></a></li>
    			<li><a href="javascript:">只周六、日配送<span></span></a></li>
    			<li><a href="javascript:">工作日、双休日均可配送<span></span></a></li>
    		</ul>
    	</div -->
        
    	<div class="p_mod o_list">
    		<h2 class="p_mod_title">支付方式</h2>
            <input type="hidden" name="paytype" id="paytype" value="alipay" />
    		<ul class="paytype">
              <li><a href="javascript:" key="alipay" class="focus">支付宝<span></span></a></li>
              <!-- <li><a href="javascript:" key="tenpay" class="">财付通<span></span></a></li>
              <li><a href="javascript:" key="outline" class="">货到付款<span></span></a></li>
              <li><a href="javascript:" key="bank" class="">网上银行<span></span></a></li> -->
           </ul>
          <!-- div class="order_address bankList" style="display:none;">
            <h3>请选择银行</h3>
            <ul class="banks">
                <input id="bank_type" name="bank_type" type="hidden" value="ICBC" />
                <li bank_value="ICBC" class="active"><span class="bank_icbc" title="中国工商银行"></span></li>
                <li bank_value="CCB"><span class="bank_ccb" title="中国建设银行"></span></li>
                <li bank_value="ABC"><span class="bank_abc" title="中国农业银行"></span></li>
                <li bank_value="CMB"><span class="bank_cmb" title="招商银行"></span></li>
                <li bank_value="BOC"><span class="bank_boc" title="中国银行"></span></li>
                <li bank_value="COMM"><span class="bank_bcom" title="交通银行"></span></li>
                <li bank_value="CEB"><span class="bank_ceb" title="中国光大银行"></span></li>
                <li bank_value="GDB"><span class="bank_gdb" title="广东发展银行"></span></li>
                <li bank_value="POSTGC"><span class="bank_post" title="中国邮政储蓄银行"></span></li>
        
                <li bank_value="CMBC"><span class="bank_cmbc" title="中国民生银行"></span></li>
                <li bank_value="SDB"><span class="bank_sdb" title="深圳发展银行"></span></li>
                <li bank_value="CITIC"><span class="bank_citic" title="中信银行"></span></li>
                <li bank_value="PAB"><span class="bank_pab" title="平安银行"></span></li>
                <li bank_value="BOB"><span class="bank_bob" title="北京银行"></span></li>     
                <li bank_value="CIB"><span class="bank_cib" title="兴业银行"></span></li>
            </ul>
          </div-->
    	</div>
    	<!--<div class="p_mod p_tips clearfix"><font class="p_ren">官方认证商铺</font><font class="p_tui">支持七天退换</font></div>-->
    	<div class="o_btn clearfix">
    		<input type="button" class="o_btn_back ts1" onclick="javascript:history.go(-1);" value="上一步" />
    		<input type="submit" class="o_btn_submit ts1" value="提交订单" />
    	</div>
     </form>
</div>
<script type="text/javascript">

$('.paytype a').click(function(){
    var key_type = $(this).attr('key');
    $('#paytype').val(key_type); 
    if (key_type == 'bank') {
        $('.bankList').show();
    } else {
        $('.bankList').hide();
    } 
    $('.paytype a').removeClass("focus");
    $(this).addClass("focus");
})

$('ul.banks li').click(function() {
    $('ul.banks li').removeClass('active');
    $(this).addClass('active');
    $('#bank_type').val($(this).attr('bank_value'));
});

function checkform(){
    var address_id = $('#address_id').val();
    if (address_id == 0 || address_id =='' ) {
        alert('请添加地址！');
        return false;
    }
}

function selectAddress(i)
{
	$("#address_list a").each(function(){
		$("#address_list a").removeClass();
	});
	$('#aid_'+i).addClass('focus');
	$('#address_id').val(i);
}
</script>
<div class="bottom_margin"></div>
<?php echo $this->partial ( 'partials/footer.phtml');?>
</body>
</html>