<!DOCTYPE HTML>
<html lang="zh-CN">
<head>
	<meta charset="utf-8" />
	<title><?php echo $this->row['name'];?></title>
	<meta name="version" content="游太网络" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0;" />
	<meta name="format-detection" content="telephone=no" />
	<link type="text/css" rel="stylesheet" href="/css/style.css" />
	<script type="text/javascript" src="/js/jquery.min.js"></script>
	<script type="text/javascript" src="/js/main.js"></script>
</head>

<body>
	<?php echo $this->partial ( 'partials/header.phtml',array('openid'=>$this->openid));?>
<!--主体-->
<div class="main">
	<div class="banner" id="banner">
		<img src="<?php echo $this->row['thumb'];?>" />
		<h1 class="p_title"><?php echo $this->row['name'];?></h1>
	</div>
	<div class="p_buy clearfix" id="p_buy">
		<span class="p_price">
			￥<?php echo $this->row['rebate'];?>
			<font class="p_price_pass">￥<?php echo $this->row['price'];?></font>
		</span>

		<!--检查库存-->
		   <a href="/product/indent?openid=<?php echo $this->openid?>&id=<?php echo $this->row['id'];?>" class="p_btn_buy">
			<span class="ts1">抢购</span>
		   </a>
			</div>
	<div class="p_tn clearfix">
		<p>
			<!--<span class="p_time">大于3天</span>-->
			<span class="p_num"><?php echo $this->row['sales'];?>人已购买</span>
		</p>
		<p class="p_show_com clearfix">
			<a href="/product/comments?openid=<?php echo $this->openid;?>&id=<?php echo $this->row['id'];?>">
				<font>商品评论（<?php echo $this->row['comment'];?>）</font>
				<span class="p_comment clearfix">
					评分
					<font class="p_com_num">8.0</font>
					<span class="p_com_b">
						<span class="p_com_t" style="width: 80%;"></span>
					</span>
				</span>
				<span class="gt"></span>
			</a>
		</p>
	</div>
	<div class="p_mod p_short_desc">
		<h2 class="p_mod_title">商品描述</h2>
		<div class="p_con">
			<?php echo htmlspecialchars_decode(stripcslashes($this->row['content']));?>
		</div>
		   <a href="#" class="p_to_desc">
			查看图文详情
			<span class="gt"></span>
		</a>
	</div>
	<div class="p_mod p_seller_info">
		<a href="/stores?openid=<?php echo $this->openid?>&id=<?php echo $this->row['shop'];?>">门店信息 <font>共<?php echo $this->countshop;?>家分店</font><span class="gt"></span></a>
	</div>
	<!--div class="p_mod p_tip">
		<h2 class="p_mod_title">特别提醒</h2>
		<div class="p_con">
			<p>
				产品咨询：商家电话：15989377520 产品咨询：商家电话：15989377520产品咨询：商家电话：15989377520 产品咨询：商家电话：15989377520 产品咨询
			</p>
		</div>
	</div-->
   <?php 
   if ($this->rows)
   {
       foreach ($this->rows as $val) {
   ?>
	<section class="i_list">
		<ul>
			<li>
				<a href="/product?openid=<?php echo $this->openid;?>&id=<?php echo $val['id'];?>">
					<img src="<?php echo $val['thumb'];?>" />
					<h3><?php echo $val['name'];?></h3>
					<p class="tui_price ts2">
						<strong>￥<?php echo $val['rebate'];?></strong>
						<del>￥<?php echo $val['price'];?></del>
						<span><cite><?php echo $val['sales'];?></cite> 人购买
						</span>
					</p>
					<?php if($val['sales']>'5'){ ?><div class="hot"><strong>热卖</strong></div><?php } ?>
				</a>
			</li>
		</ul>
	</section>
	<?php
	 } 
   }
	?>
	    <div class="p_mod p_seller_info p_tips ts2"><a href="">更多精彩抢购<span class="gt"></span></a></div>
	<!--<div class="p_mod p_tips clearfix">
		<font class="p_ren">官方认证商铺</font>
		<font class="p_tui">支持七天退换</font>
	</div>-->
</div>
<script type="text/javascript">
window.onload = function(){
	//价格与抢购按钮浮动
	var f_obj = document.getElementById('p_buy');
	var f_y = f_obj.offsetTop;
	var f_class = f_obj.className;
	document.onscroll = function(){
		if(document.body.scrollTop>f_y){
			f_obj.className += " fixed_t";
		}else{
			f_obj.className = f_class;
		}
	}
	img_size();
}

function img_size(){
    var banner_box = document.getElementById("banner");
    var _img = banner_box.getElementsByTagName('img');
    _img[0].style.maxWidth = document.body.clientWidth+"px";
    _img[0].style.maxHeight = (document.body.clientWidth)/2+"px";
}
</script>
<?php echo $this->partial ( 'partials/footer.phtml');?>
</body>
</html>