<!DOCTYPE HTML>
<html lang="zh-CN">
<head>
	<meta charset="utf-8" />
	<title>搜索列表</title>
	<meta name="version" content="游太网络" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0;" />
	<meta name="format-detection" content="telephone=no" />
	<link type="text/css" rel="stylesheet" href="/css/style.css" />
	<link type="text/css" rel="stylesheet" href="/css/comindex.css" />
	<script type="text/javascript" src="/js/jquery.min.js"></script>
	<script type="text/javascript" src="/js/main.js"></script>
</head>

<body>
	<?php echo $this->partial ( 'partials/header.phtml',array('openid'=>$this->openid,'keywords'=>$this->keywords));?>
<!--主体-->
<section class="i_list">
		<ul id="product_list">
		<?php 
		if($this->stotal==0) echo "<li>暂时没有您要查询的结果！</li>";
		if ($this->rows)
		{
			foreach ($this->rows as $val) {
		?>
		<li>
			<a href="/product?openid=<?php echo $this->openid?>&id=<?php echo $val['id'];?>">
				<img src="<?php echo $val['thumb'];?>" />
				<h3><?php echo str_replace($this->keywords, '<span class="font_reds reds">'.$this->keywords.'</span>', $val['name']);?></h3>
				<p class="tui_price ts2"><strong>￥<?php echo $val['rebate'];?></strong><del>￥<?php echo $val['price'];?></del><span><cite><?php echo $val['sales'];?></cite>人购买</span></p>
				<?php if($val['sales']>'5'){ ?><div class="hot"><strong>热卖</strong></div><?php } ?>
			</a>
		</li>
		<?php 
		      }
		}
		?>
		</ul>
	</section>
	<?php if($this->pageCount > 1) {?>
<a class="more" page="2" href="javascript:void(0);">加载更多</a>
<script type="text/javascript">
  $(function(){
      var pageCount = <?php echo $this->pageCount;?>;
      $('.more').click(function(){
          var page=$('.more').attr('page');
          $.post("/stores/more?openid=<?php echo $this->openid;?>&do=&id=<?php echo $this->id;?>&keywords=<?php echo $this->keywords;?>&page="+page, { "time": <?php echo time();?>},function(o){
               $('.i_list ul').append(o); 
          });
          page++;
          if (pageCount < page)
          {
              $('.more').hide();
              return false;
          }
          $('.more').attr('page',page);
      });
  });
</script>
<?php }?>
<?php echo $this->partial ( 'partials/footer.phtml');?>
</body>
</html>