<div class="header">
	<h1 class="page-title">添加商铺</h1>
</div>

<ul class="breadcrumb">
	<li><a href="/home">首页</a> <span class="divider">/</span></li>
	<li><a href="/tenant/create">商铺列表</a> <span class="divider">/</span></li>
	<li class="active">添加商铺</li>
</ul>

<div class="container-fluid">
	<div class="row-fluid">
<form id="tab" name="createUser" method="post" action="" enctype="multipart/form-data">
		<div class="btn-toolbar">
		    <input type="submit" name="submit" id="submit"  class="btn btn-primary" value="提交" />
			<div class="btn-group"></div>
		</div>
		<div class="well">
			<ul class="nav nav-tabs">
				<li class="active"><a href="#home" data-toggle="tab">基础配置</a></li>
				<li><a href="#profile" data-toggle="tab">密码设置</a></li>
			</ul>
			
			<div id="myTabContent" class="tab-content">
			
				<div class="tab-pane active in" id="home">
					
						<label>昵称</label> 
						<input type="text" value="" name="username" class="input-xlarge"> 
						<label>用户名</label> 
						<input type="text" value="" name="realname" class="input-xlarge"> 
						<label>邮箱</label> 
						<input type="text" value="" name="email" class="input-xlarge">
						<label>电话</label> 
						<input type="text" value="" name="email" class="input-xlarge">
						<!-- <label for="fileField">上传</label>
                        <input type="file" name="fileField" id="fileField" /> -->
				</div>
				<div class="tab-pane fade" id="profile">
					
						<label>密码</label> <input type="password" name="password" class="input-xlarge">
						<label>确认密码</label> <input type="password" name="repassword" class="input-xlarge">
					
				</div>
				
			</div>

		</div>
		<?php echo $this->partial('partials/homeFooter.phtml')?>
</form>
	</div>
</div>