<!DOCTYPE HTML>
<html lang="zh-CN">
<head>
	<meta charset="utf-8" />
	<title>分类</title>
	<meta name="version" content="游太网络" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0;" />
	<meta name="format-detection" content="telephone=no" />
	<link type="text/css" rel="stylesheet" href="css/style.css" />
	<script type="text/javascript" src="js/jquery.min.js"></script>
	<script type="text/javascript" src="js/main.js"></script>
</head>

<body>
	<?php echo $this->partial ( 'partials/header.phtml',array('openid'=>$this->openid));?>
<!--主体-->
<section class="c_list">
	<h1>全部分类：</h1>
	<?php 
	if ($this->rows)
	{
		foreach ($this->rows as $val) {
	?>
	<dl>
		<dt>
			<a href="/product/list?openid=<?php echo $this->openid;?>&id=<?php echo $val['id'];?>">
				<?php echo $val['name'];?>
				<i></i>
			</a>
		</dt>
	</dl>
	<?php 
	   }
	}
	?>
		</section>
<?php echo $this->partial ( 'partials/footer.phtml');?>
</body>
</html>