<!DOCTYPE HTML>
<html lang="zh-CN">
<head>
	<meta charset="utf-8" />
	<title>商圈</title>
	<meta name="version" content="游太网络" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0;" />
	<meta name="format-detection" content="telephone=no" />
	<link type="text/css" rel="stylesheet" href="css/style.css" />
	<script type="text/javascript" src="js/jquery.min.js"></script>
	<script type="text/javascript" src="js/main.js"></script>
</head>

<body>
	<?php echo $this->partial ( 'partials/header.phtml',array('openid'=>$this->openid));?>
<!--主体-->
<section class="i_list">
		<ul class="i_shop_list">
		<?php 
		if ($this->rows)
		{
		    foreach ($this->rows as $val) {
		?>
		<li>
			<a href="/stores?openid=<?php echo $this->openid;?>&id=<?php echo $val['id'];?>">
				<img src="<?php echo $val['thumb'];?>" />
				<h3><?php echo $val['shopname'];?></h3>
			</a>
			<p class="i_shop_phone">
				<a href="tel:<?php echo $val['tel'];?>"><?php echo $val['tel'];?></a>
			</p>
			<p class="i_shop_address">
				<a href="">地址：<?php echo $val['address']?></a>
			</p>
            <span class="gt"></span>
		</li>
		<?php 
		 }
        }
		?>
		</ul>
	</section>
		<?php if($this->pageCount>1) {?>
<a class="more" page="2" href="javascript:void(0);">加载更多</a>
<script type="text/javascript">
$(function() {
	var pageCount = <?php echo $this->pageCount;?>;
	$('.more').click(function(){
        var page = $(this).attr('page');
        $.post("/business/more?openid=<?php echo $this->openid;?>&page="+page, { "time": <?php echo time();?> },function(data){
                $('.i_shop_list').append(data);
                page++;
                $('.more').attr('page',page);
                
            });
        if (page>=pageCount)
        {
           $(this).hide(); 
        }
	});
});
</script>
<?php }?>
<?php echo $this->partial ( 'partials/footer.phtml');?>
</body>
</html>