<div class="dh dhf ">
 <ul> 
 <li> <a href="/?openid=<?php echo $this->openid;?>&ref=footer_index" <?php if($_GET['ref']=="footer_index" || $_GET['ref']=="") echo 'class="con"';?>> <span class="shouye"></span> <span>首页</span> </a> </li> 
 <li> <a href="/type?openid=<?php echo $this->openid;?>&ref=footer_type" <?php if($_GET['ref']=="footer_type") echo 'class="con"';?>> <span class="fenlei"></span> <span>分类</span></a> </li> 
 <li> <a href="/business?openid=<?php echo $this->openid;?>&ref=footer_business" <?php if($_GET['ref']=="footer_business") echo 'class="con"';?>> <span class="shoucj"></span> <span>商圈</span></a> </li> 
 <li> <a href="/user/indent?openid=<?php echo $this->openid;?>&s=2&ref=footer_carts" <?php if($_GET['ref']=="footer_carts") echo 'class="con"';?>> <span class="gouwuc"></span> <span>购物车</span></a> </li> 
 <li> <a href="/user?openid=<?php echo $this->openid;?>&ref=footer_member" <?php if($_GET['ref']=="footer_member") echo 'class="con"';?>> <span class="myfk"></span> <span>会员中心</span></a> </li> 
 </ul> 
</div> 
  
<footer>
	<p>&copy; 2013 游太网络技术服务</p>
	<p><a href="/?openid=<?php echo $this->openid;?>">首页</a><a href="/user/about?openid=<?php echo $this->openid;?>">关于我们</a><a href="/user/contact?openid=<?php echo $this->openid;?>">联系我们</a></p>
</footer>
<div class="bottom_margin"></div>