<!--头部-->
	<header class="ts1">
	<?php 
	if($this->keywords) { 
?>
		<ul class="u_home fl">
		  <li><a href="#" class="color:#fff"><?php echo $this->keywords;?></a></li>
		</ul>
		<?php }else{ ?>
		<a class="u_back fl" href="javascript:history.go(-1)">返回</a>
		<?php } ?>
		<ul class="topbar fr">
			<li>
				<a class="icon_user" href="/user?openid=<?php echo $this->openid;?>"><i></i>我的</a>
			</li>
			<li>
				<a class="icon_shang" href="/business?openid=<?php echo $this->openid;?>"><i></i>商圈</a>
			</li>
			<li>
				<a class="icon_class" href="/type?openid=<?php echo $this->openid;?>"><i></i>分类
				</a>
			</li>
		</ul>
	</header>