<div>
				<ul class="breadcrumb">
					<li>
						<a href="/home">首页</a> <span class="divider">/</span>
					</li>
					<li>
						<a href="/collect">采集列表</a>
					</li>
				</ul>
			</div>
		<div class="row-fluid sortable ui-sortable">
				<div class="box span12">
					<div class="box-header well" data-original-title="">
						<h2><i class="icon-edit"></i> 添加采集</h2>
						<div class="box-icon">
							<a href="javascript:void(0);" class="btn btn-setting btn-round"><i class="icon-cog"></i></a>
						</div>
					</div>
					<div class="box-content">
						<form class="form-horizontal" name="formCollect" method="post" action="">
							<fieldset>
							<legend>列表部分    </legend>
							  <div class="control-group">
								<label class="control-label" for="name">名称</label>
								<div class="controls">
								  <input class="input-xlarge focused" name="name" id="name" type="text" value="">
								</div>
							  </div>
							  <div class="control-group">
								<label class="control-label" for="url">网址</label>
								<div class="controls">
								  <input class="input-xlarge focused" name="url" id="url" type="text" value="">
								  从 <input class="input-mini" name="rule[url_start]" type="text" id="url_start" size="5" />
								  到 <input class="input-mini" name="rule[urlEnd]" type="text" id="url_end" size="5" />
								</div>
							  </div>
							  <div class="control-group">
								<label class="control-label" for="limits">开始范围</label>
								<div class="controls">
								  <textarea name="rule[limits]" id="limits" style="margin: 0px; height: 54px; width: 271px; "></textarea>
								</div>
							  </div>
							  <div class="control-group">
								<label class="control-label" for="contain">地址 </label>
								<div class="controls">
									 <input type="text" name="rule[contain]" id="contain" /> 含
									 <input type="text" name="rule[exclusive]" id="exclusive" /> 不含
								</div>
							  </div>
							  <div class="control-group">
								<label class="control-label" for="disabledInput">地址替换</label>
								<div class="controls">
								  <textarea name="rule[urlReplace]" id="urlReplace" style="margin: 0px; height: 54px; width: 271px; "></textarea>
								</div>
							  </div>
							  <div class="form-actions">
							    <input type="submit" class="btn btn-primary" value="保存" />
								<input class="btn" type="submit" name="urlTest" id="urlTest" value="测试" />
							  </div>
							  <legend>内容部分  </legend>
							  <div class="control-group">
								<label class="control-label" for="testUrl">测试网址</label>
								<div class="controls">
								  <input class="input-xlarge focused" name="rule[url]" id="testUrl" type="text" value="">
								</div>
							  </div>
							  <div class="control-group">
								<label class="control-label" for="disabledInput">标题</label>
								<div class="controls">
								 <textarea name="rule[title]" id="title" style="margin: 0px; height: 54px; width: 271px; "></textarea>
								  过滤 <textarea name="rule[titleFilter]" id="titleFilter" style="margin: 0px; height: 54px; width: 271px; "></textarea>
								  替换 <textarea name="rule[titleReplace]" id="titleReplace" style="margin: 0px; height: 54px; width: 271px; "></textarea>
								</div>
							  </div>
							  <div class="control-group">
								<label class="control-label">关键字</label>
								<div class="controls">
								  <textarea name="rule[keywords]" id="keywords" style="margin: 0px; height: 54px; width: 271px; "></textarea>
								  过滤 <textarea name="rule[keywordsFilter]" id="keywordsFilter" style="margin: 0px; height: 54px; width: 271px; "></textarea>
								  替换 <textarea name="rule[keywordsReplace]" id="keywordsReplace" style="margin: 0px; height: 54px; width: 271px; "></textarea>
								</div>
							  </div>
							  <div class="control-group">
								<label class="control-label">描述</label>
								<div class="controls">
								  <textarea name="rule[description]" id="description" style="margin: 0px; height: 54px; width: 271px; "></textarea>
								  过滤 <textarea name="rule[descriptionFilter]" id="descriptionFilter" style="margin: 0px; height: 54px; width: 271px; "></textarea>
								  替换 <textarea name="rule[descriptionReplace]" id="descriptionReplace" style="margin: 0px; height: 54px; width: 271px; "></textarea>
								</div>
							  </div>
							  <div class="control-group">
								<label class="control-label">内容</label>
								<div class="controls">
								  <textarea name="rule[content]" id="content" style="margin: 0px; height: 54px; width: 271px; "></textarea>
								  过滤 <textarea name="rule[contentFilter]" id="contentFilter" style="margin: 0px; height: 54px; width: 271px; "></textarea>
								  替换 <textarea name="rule[contentReplace]" id="contentReplace" style="margin: 0px; height: 54px; width: 271px; "></textarea>
								</div>
							  </div>
							  <div class="control-group">
								<label class="control-label" for="optionsCheckbox2">纯文本</label>
								<div class="controls">
								  <label class="checkbox">
									<div class="checker disabled" id="uniform-optionsCheckbox2"><span>
									<input type="checkbox" name="rule[text]" id="text" value="1" style="opacity: 0; "></span>
									</div>
								  </label>
								</div>
							  </div>
							  <div class="control-group">
								<label class="control-label" for="disabledInput">分页</label>
								<div class="controls">
								  <textarea name="rule[paging]" id="paging" style="margin: 0px; height: 54px; width: 271px; "></textarea>
								</div>
							  </div>
							 <div class="form-actions">
								<input type="submit" class="btn btn-primary" value="保存" />
								<input class="btn" type="submit" name="contentTest" id="contentTest" value="测试" />
							  </div>
							</fieldset>
						  </form>
					
					</div>
				</div><!--/span-->
			
			</div><!--/row-->