<div>
				<ul class="breadcrumb">
					<li>
						<a href="#">Home</a> <span class="divider">/</span>
					</li>
					<li>
						<a href="#">Tables</a>
					</li>
				</ul>
			</div>
			<div class="alert alert-error"><i class="icon-exclamation-sign"></i>  阿斯顿发撒旦法撒旦法</div>
			<div class="row-fluid sortable">		
				<div class="box span12">
					<div class="box-header well" data-original-title>
						<h2><i class="icon-list-alt"></i> 测试数据</h2>
					</div>
					<div class="box-content">
						<table class="table">
							  <thead>
								  <tr>
									  <th>标题</th>
									  <th>地址</th>
									  <th>测试</th>
								  </tr>
							  </thead>   
							  <tbody>
								<tr>
									<td>Muhammad Usman</td>
									<td class="center">2012/01/01</td>
									<td class="center">Member</td>
								</tr>
							  </tbody>
						 </table>            
					</div>
				</div><!--/span-->
			
			</div>