<div class="header">
	<h1 class="page-title">订单列表</h1>
</div>

<ul class="breadcrumb">
	<li><a href="/home">首页</a> <span class="divider">/</span></li>
	<li><a href="/indent?s=3">订单列表</a> <span class="divider">/</span></li>
	<li class="active">
	<?php 
	echo $this->status[$this->s];
	?>
	</li>
</ul>

<div class="container-fluid">
	<div class="row-fluid">
	    <?php 
	    if ($this->success)
	    {
	    	echo "<div class=\"alert alert-success\">
	    	<a class=\"close\" data-dismiss=\"alert\">×</a>
	    	<strong>{$this->success->title}</strong>  {$this->success->message}</div>";
	    }
	    ?>
	    <div class="btn-toolbar">
			<a href="?s=2" class="btn btn-primary"> 未付款</a>
			<a href="?s=1" class="btn btn-primary"> 已付款</a>
			<a href="?s=3" class="btn btn-primary"> 已退款</a>
			<a href="?s=4" class="btn btn-primary"> 已发货</a>
			<div class="btn-group"></div>
		</div>
		<div class="well">
			<table class="table">
				<thead>
					<tr>
						<th width="10%">订单号</th>
						<th>商品名称</th>
						<th width="5%">数量</th>
						<th width="5%">金额</th>
						<th width="10%">生成时间</th>
						<th width="8%">状态</th>
						<th width="8%">支付方式</th>
						<?php if ($this->s != 2 ) echo '<th width="10%">支付时间</th><th width="10%">物流信息</th>';?>
						<th style="width: 45px;">改/删</th>
					</tr>
				</thead>
				<tbody>
				<?php 
				if ($this->rows)
				{
					foreach ($this->rows as $val) {
				?>
					<tr id="tid_<?php echo $val['id'];?>">
						<td><?php echo $val['serialnumber'];?></td>
						<td><?php echo $val['name'];?></td>
						<td><?php echo $val['amount'];?></td>
						<td><?php echo $val['sum'];?></td>
						<td><?php echo date("Y-m-d",$val['addtime']);?></td>
						<td><?php echo $this->status[$val['status']]; ?></td>
						<td><?php echo $val['payment']=='alipay'?'支付宝':$val['payment'];?></td>
						<?php if ($this->s != 2) echo "<td>{$val['payTime']}</td><th width=\"10%\">物流信息</th>";?>
						<td><a href="/indent/edit?id=<?php echo $val['id'];?>"><i class="icon-pencil"></i></a> &nbsp;
						<a href="#myModal" role="button" data-toggle="modal" onclick="remove(<?php echo $val['id'];?>);"><i class="icon-remove"></i></a></td>
					</tr>
					<?php 
					   }
				 }
					?>
				</tbody>
			</table>
		</div>
		
		<?php 
		  echo $this->paginationControl($this->rows, 'Sliding', 'pagination/pagination.phtml');
        ?>
        <script type="text/javascript">
           function remove(i){
                 $('#remove').attr('onclick','delIndent('+ i +')');
               }
             function delIndent(i)
             {
                 $.post('/indent/delete?id='+i,{'id':i},function(data){
                     if (data.isok==true)
                     {
                    	 $('#tid_'+i).hide();
                     }
                 },'json');
             }
		   </script>
		<div class="modal small hide fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
				<h3 id="myModalLabel">删除订单</h3>
			</div>
			<div class="modal-body">
				<p class="error-text">
					<i class="icon-warning-sign modal-icon"></i>
					确认删除当前订单？
				</p>
			</div>
			<div class="modal-footer">
				<button class="btn" data-dismiss="modal" aria-hidden="true">取消</button>
				<button class="btn btn-danger" id="remove" data-dismiss="modal">确认</button>
			</div>
		</div>
		<?php echo $this->partial('partials/homeFooter.phtml');?>
	</div>
</div>