<?php 
      $children = $this->viewModel()->getCurrent()->getChildren();
      $child = $children[0];
?>
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>SCRM管理系统</title>
<meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="">
<meta name="author" content="">
<link rel="stylesheet" type="text/css" href="/lib/bootstrap/css/bootstrap.css">
<link rel="stylesheet" type="text/css" href="/css/theme.css">
<link rel="stylesheet" href="/lib/font-awesome/css/font-awesome.css">
<?php 
if (isset($child->asset))
{
	if (isset($child->asset['css']) && is_array($child->asset['css']))
	{
		foreach ($child->asset['css'] as $val) {
			echo "<link rel=\"stylesheet\" href=\"{$val}\">".PHP_EOL;
		}
	    
	}
}
?>
<script src="/lib/jquery-1.7.2.min.js" type="text/javascript"></script>
<style type="text/css">
#line-chart {
	height: 300px;
	width: 800px;
	margin: 0px auto;
	margin-top: 1em;
}
.brand {
	font-family: georgia, serif;
}
.brand .first {
	color: #ccc;
	font-style: italic;
}
.brand .second {
	color: #fff;
	font-weight: bold;
}
</style>
<!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
<!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
</head>

<!--[if lt IE 7 ]> <body class="ie ie6"> <![endif]-->
<!--[if IE 7 ]> <body class="ie ie7 "> <![endif]-->
<!--[if IE 8 ]> <body class="ie ie8 "> <![endif]-->
<!--[if IE 9 ]> <body class="ie ie9 "> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!-->
<body class="">
<!--<![endif]-->

<div class="navbar">
  <div class="navbar-inner">
    <ul class="nav pull-right">
      <!-- <li><a href="#" class="hidden-phone visible-tablet visible-desktop"		role="button">设置</a></li> -->
      <li id="fat-menu" class="dropdown"><a href="#" role="button" class="dropdown-toggle" data-toggle="dropdown"> 
      <i class="icon-user"></i>
      <?php echo $child->user->realname;?><i class="icon-caret-down"></i> </a>
        <ul class="dropdown-menu">
          <li><a tabindex="-1" href="/users/edit?id=<?php echo $child->user->id;?>">我的账号</a></li>
          <li class="divider"></li><li><a tabindex="-1" href="/users/config">基本设置</a></li>
          <li class="divider"></li>
          <li><a tabindex="-1" href="/<?php echo $child->user->domain;?>/logout">退出系统</a></li>
        </ul>
      </li>
    </ul>
    <a class="brand" href="/home"><!-- <span class="first">微信</span>  --><span	class="second">SCRM管理平台</span></a> </div>
</div>
<div class="sidebar-nav"> 
  <a href="#dashboard-menu" class="nav-header collapsed" data-toggle="collapse"><i class="icon-home"></i>控制面板<i class="icon-chevron-up"></i></a>
  <ul id="dashboard-menu" class="nav nav-list collapse">
    <li><a href="/home">控制主页</a></li>
    <li><a href="/users/edit?id=<?php echo $child->user->id;?>">账号设置</a></li>
    <li><a href="/users/config">基本配置</a></li>
  </ul>
 
 <a href="#archives-menu" class="nav-header" data-toggle="collapse"><i class="icon-tags"></i>内容管理<i class="icon-chevron-up"></i></a>
  <ul id="archives-menu" class="nav nav-list collapse in">
    <li><a href="/admin/archives?time=<?php echo time();?>">内容列表</a></li>
    <li><a href="/admin/archives/create?time=<?php echo time();?>">添加内容</a></li>
  </ul>
  
  <a href="#auto-menu" class="nav-header" data-toggle="collapse"><i class="icon-tags"></i>车型管理<i class="icon-chevron-up"></i></a>
  <ul id="auto-menu" class="nav nav-list collapse in">
    <li><a href="/auto?time=<?php echo time();?>">车型列表</a></li>
    <li><a href="/auto/create?time=<?php echo time();?>">添加车型</a></li>
  </ul>
  
  <a href="#type-menu" class="nav-header" data-toggle="collapse"><i class="icon-tags"></i>管理分类<i class="icon-chevron-up"></i></a>
  <ul id="type-menu" class="nav nav-list collapse">
    <li><a href="/t">分类列表</a></li>
    <li><a href="/t/create">添加分类</a></li>
  </ul>
  
  <a href="#commodity-menu" class="nav-header" data-toggle="collapse"><i class="icon-tags"></i>商品管理<i class="icon-chevron-up"></i></a>
  <ul id="commodity-menu" class="nav nav-list collapse">
    <li><a href="/commodity">商品列表</a></li>
    <li><a href="/commodity/welcome/">欢迎推荐</a></li>
    <li><a href="/commodity/create">添加商品</a></li>
  </ul>
  

  <a href="#tenant-menu" class="nav-header"data-toggle="collapse"><i class="icon-user"></i>账号管理<i class="icon-chevron-up"></i></a>
  <ul id="tenant-menu" class="nav nav-list collapse">
    <li><a href="/users">管理账号</a></li>
    <li><a href="/users/create">添加账号</a></li>
  </ul>
  
  <a href="#tenant-menu" class="nav-header"data-toggle="collapse"><i class="icon-exclamation-sign"></i>提示信息<i class="icon-chevron-up"></i></a>
  <ul id="tenant-menu" class="nav nav-list collapse">
    <li><a href="/msg">提示列表</a></li>
    <li><a href="/msg/create">添加提示</a></li>
  </ul>
 <a href="/indent" class="nav-header"><i class="icon-shopping-cart"></i>订单管理</a>

  <a href="#accounts-menu" class="nav-header" data-toggle="collapse"><i class="icon-pencil"></i>用户提交<!-- <span class="label label-info">+3</span> --></a>
  <ul id="accounts-menu" class="nav nav-list collapse">
    <li><a href="/keyword">文本消息</a></li>
    <li><a href="/keyword/images">图片消息</a></li>
    <li><a href="/keyword/location">位置消息</a></li>
    <li><a href="/keyword/link">链接消息</a></li>
  </ul>
  <a href="#askboard-menu" class="nav-header  collapsed" data-toggle="collapse"><i class="icon-edit"></i>有问必答<i class="icon-chevron-up"></i></a>
  <ul id="askboard-menu" class="nav nav-list collapse">
    <li><a href="/answers/create">提交问题</a></li>
    <li><a href="/answers">问题列表</a></li>
  </ul>
</div>
<div class="content"> <?php echo $this->content;?> </div>
<script src="/lib/bootstrap/js/bootstrap.js"></script> 
<?php 
if (isset($child->asset))
{
    if (isset($child->asset['js']) && is_array($child->asset['js']))
    {
        foreach ($child->asset['js'] as $val) {
        	echo "<script src=\"{$val}\"></script>".PHP_EOL;
        }
    }
}
?>
<script type="text/javascript">
        $("[rel=tooltip]").tooltip();
        $(function() {
            $('.demo-cancel-click').click(function(){return false;});
        });
    </script>
</body>
</html>