<div class="header">
	<!-- <div class="stats">
		<p class="stat">
			<span class="number">53</span>tickets
		</p>
		<p class="stat">
			<span class="number">27</span>tasks
		</p>
		<p class="stat">
			<span class="number">15</span>waiting
		</p>
	</div> -->

	<h1 class="page-title">控制面板</h1>
</div>

<ul class="breadcrumb">
	<li><a href="/home">首页</a> <span class="divider">/</span></li>
	<li class="active">控制面板</li>
</ul>

<div class="container-fluid">
	<div class="row-fluid">
		<div class="row-fluid">
            <?php 
            if ($this->auth)
            {
            	echo "<div class=\"alert alert-info\"><button type=\"button\" class=\"close\" data-dismiss=\"alert\">×</button> <strong>{$this->auth->title}:</strong>{$this->auth->message}</div>";
            }
            ?>
            <!-- 
			<div class="block">
				<a href="#page-stats" class="block-heading" data-toggle="collapse">预览统计</a>
				<div id="page-stats" class="block-body collapse in">

					<div class="stat-widget-container">
						<div class="stat-widget">
							<div class="stat-button">
								<p class="title">2500</p>
								<p class="detail">用户数量</p>
							</div>
						</div>

						<div class="stat-widget">
							<div class="stat-button">
								<p class="title">2344</p>
								<p class="detail">门店数量</p>
							</div>
						</div>

						<div class="stat-widget">
							<div class="stat-button">
								<p class="title">153040</p>
								<p class="detail">商品数量</p>
							</div>
						</div>

						<div class="stat-widget">
							<div class="stat-button">
								<p class="title">12675213</p>
								<p class="detail">用户提交</p>
							</div>
						</div>

					</div>
				</div>
			</div>
		</div>
 -->
		<!--  <div class="row-fluid">
			<div class="block span6">
				<a href="#tablewidget" class="block-heading" data-toggle="collapse">最新关键字<span
					class="label label-warning">+10</span></a>
				<div id="tablewidget" class="block-body collapse in">
					<table class="table">
						<thead>
							<tr>
								<th>First Name</th>
								<th>Last Name</th>
								<th>Username</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<td>Mark</td>
								<td>Tompson</td>
								<td>the_mark7</td>
							</tr>
							<tr>
								<td>Ashley</td>
								<td>Jacobs</td>
								<td>ash11927</td>
							</tr>
							<tr>
								<td>Audrey</td>
								<td>Ann</td>
								<td>audann84</td>
							</tr>
							<tr>
								<td>John</td>
								<td>Robinson</td>
								<td>jr5527</td>
							</tr>
							<tr>
								<td>Aaron</td>
								<td>Butler</td>
								<td>aaron_butler</td>
							</tr>
							<tr>
								<td>Chris</td>
								<td>Albert</td>
								<td>cab79</td>
							</tr>
						</tbody>
					</table>
					<p>
						<a href="users.html">More...</a>
					</p>
				</div>
			</div>
			<div class="block span6">
				<a href="#widget1container" class="block-heading"
					data-toggle="collapse">最新通知</a>
				<div id="widget1container" class="block-body collapse in">
					<h2>系统更新</h2>
					2013-06-06 系统更新
				</div>
			</div>
		</div>

		<div class="row-fluid">
			<div class="block span6">
				<div class="block-heading">
					<span class="block-icon pull-right"> <a href="#"
						class="demo-cancel-click" rel="tooltip" title="Click to refresh"><i
							class="icon-refresh"></i></a>
					</span> <a href="#widget2container" data-toggle="collapse">最新用户</a>
				</div>
				<div id="widget2container" class="block-body collapse in">
					<table class="table list">
						<tbody>
							<tr>
								<td>
									<p>
										<i class="icon-user"></i> Mark Otto
									</p>
								</td>
								<td>
									<p>Amount: $1,247</p>
								</td>
								<td>
									<p>Date: 7/19/2012</p> <a href="#">View Transaction</a>
								</td>
							</tr>
							<tr>
								<td>
									<p>
										<i class="icon-user"></i> Audrey Ann
									</p>
								</td>
								<td>
									<p>Amount: $2,793</p>
								</td>
								<td>
									<p>Date: 7/12/2012</p> <a href="#">View Transaction</a>
								</td>
							</tr>
							<tr>
								<td>
									<p>
										<i class="icon-user"></i> Mark Tompson
									</p>
								</td>
								<td>
									<p>Amount: $2,349</p>
								</td>
								<td>
									<p>Date: 3/10/2012</p> <a href="#">View Transaction</a>
								</td>
							</tr>
							<tr>
								<td>
									<p>
										<i class="icon-user"></i> Ashley Jacobs
									</p>
								</td>
								<td>
									<p>Amount: $1,192</p>
								</td>
								<td>
									<p>Date: 1/19/2012</p> <a href="#">View Transaction</a>
								</td>
							</tr>

						</tbody>
					</table>
				</div>
			</div>
			<div class="block span6">
				<p class="block-heading">系统信息</p>
				<div class="block-body">
					<h2>系统信息</h2>
					加载中...
				</div>
			</div>
		</div>
		-->
		 <?php 
		 echo $this->partial('partials/homeFooter.phtml');
		 ?>
	</div>
</div>