<div class="header">
	<h1 class="page-title">基本配置</h1>
</div>

<ul class="breadcrumb">
	<li><a href="/home" >首页</a> <span class="divider">/</span></li>
	<li class="active">基本配置</li>
</ul>

<div class="container-fluid">
	<div class="row-fluid">
	    <?php 
    	if ($this->success)
    	{
    		echo "<div class=\"alert alert-success\">
            <a class=\"close\" data-dismiss=\"alert\">×</a>
            <strong>{$this->success->title}</strong>  {$this->success->message}</div>";
    	}
    	?>
		<form id="tab" name="createUser" method="post" action="" onsubmit="return clickForm();">
			<div class="btn-toolbar">
				<input type="submit" name="submit" id="submit"
					class="btn btn-primary " value="提交" />
				<div class="btn-group"></div>
			</div>
			<div class="well">
				<ul class="nav nav-tabs">
					<li class="active"><a href="#home" data-toggle="tab">基础配置</a></li>
					<?php if ($this->user->power >=2) echo '<li><a href="#profile" data-toggle="tab">更多配置</a></li>';?>
				</ul>

				<div id="myTabContent" class="tab-content">
					<div class="tab-pane active in" id="home">
						<div class="control-group" id="group-realname">
							<label class="control-label" for="realname">名称</label>
							<div class="controls">
								<input type="text" value="<?php echo $this->row['realname'];?>" name="realname" id="realname"
									class="span3"> <span class="help-inline" id="help-realname"></span>
							</div>
						</div>

						<div class="control-group" id="group-email">
							<label class="control-label" for="email">邮箱</label>
							<div class="controls">
								<input type="text" value="<?php echo $this->row['email'];?>" name="email" id="email"
									class="span3"> <span class="help-inline" id="help-email"></span>
							</div>
						</div>

						<div class="control-group" id="group-tel">
							<label class="control-label" for="tel">电话</label>
							<div class="controls">
								<input type="text" value="<?php echo $this->row['tel'];?>" name="tel" id="tel" class="span3"> <span
									class="help-inline" id="help-tel"></span>
							</div>
						</div>

						<div class="control-group" id="group-city">
							<label class="control-label" for="city">省(市)</label>
							<div class="controls">
            				 <select name="city" class="span2" id="city" onchange="parent(this.value);">
                              <option value="">请选择</option>
                              <?php
                                                if ($this->areas) {
                                                    foreach ($this->areas as $val) {
            											echo "<option value=\"{$val['areaid']}\"";
            											if ($this->row['city']==$val['areaid']) echo 'selected="selected"';
            											echo ">{$val['name']}</option>".PHP_EOL;
            										}
                                                }
                                                ?>
                            </select> <span class="help-inline" id="help-city"></span>
							</div>
						</div>

						<div class="control-group" id="group-area">
							<label class="control-label" for="area">市(区)</label>
							<div class="controls">
								<select name="area" class="span2" id="area">
                                <?php 
                						if (isset($this->city))
                						{
                							foreach ($this->city as $val) {
                								echo "<option value=\"{$val['areaid']}\"";
                								if ($this->row['area']==$val['areaid']) echo 'selected="selected"';
                								echo ">{$val['name']}</option>".PHP_EOL;
                							}
                						}
                				?>
                                </select>
                 <span class="help-inline" id="help-area"></span>
							</div>
						</div>

						<div class="control-group" id="group-address">
							<label class="control-label" for="address">地址</label>
							<div class="controls">
								<input type="text" value="<?php echo $this->row['address'];?>" name="address" id="address" class="span3"> 
								<span class="help-inline" id="help-address"></span>
							</div>
						</div>

					</div>
					<?php 
					if ($this->user->power >=2)
					{
					?>
					<div class="tab-pane fade" id="profile">
					
					    <div class="control-group" id="group-sitename">
							<label class="control-label" for="sitename">网站名称</label>
							<div class="controls">
								<input type="text" value="<?php echo $this->row['sitename'];?>" name="sitename" id="sitename" class="span3" > 
								<span class="help-inline" id="help-sitename"></span>
							</div>
						</div>
					
					    <div class="control-group" id="group-PID">
							<label class="control-label" for="PID">支付宝(PID)</label>
							<div class="controls">
								<input type="text" value="<?php echo $this->row['PID'];?>" name="PID" id="PID" class="span3" > 
								<span class="help-inline" id="help-PID"></span>
							</div>
						</div>
						<div class="control-group" id="group-KEY">
							<label class="control-label" for="KEY">支付宝(KEY)</label>
							<div class="controls">
								<input type="text" value="<?php echo $this->row['KEY'];?>" name="KEY" id="KEY" class="span3" > 
								<span class="help-inline" id="help-KEY"></span>
							</div>
						</div>
						<div class="control-group" id="group-alipayEmail">
							<label class="control-label" for="alipayEmail">支付宝邮箱</label>
							<div class="controls">
								<input type="text" value="<?php echo $this->row['alipayEmail'];?>" name="alipayEmail" id="alipayEmail" class="span3" > 
								<span class="help-inline" id="help-alipayEmail"></span>
							</div>
							<?php 
							if ($this->row['PID'] && $this->row['KEY'] && $this->row['alipayEmail'])
							{
								echo "<a href=\"/users/alipay\" target=\"_blank\">绑定支付宝，测试支付</a>";
							}
							?>
						</div>
						<div class="control-group" id="group-wc">
                          <label class="control-label" for="wc">欢迎词方式</label>
                          <div class="controls">
                            文本方式 <input type="radio" value="1" name="wc" id="wc_1" <?php echo $this->row['wc'] == 1?'checked':'';?> />    
            			    产品列表 <input type="radio" value="2" name="wc" id="wc_2" <?php echo $this->row['wc'] == 2?'checked':'';?> /> 
                           </div>
                        </div>
                        
                        <div class="control-group" id="group-welcome">
                          <label class="control-label" for="welcome">欢迎词</label>
                          <div class="controls">
                            <textarea name="welcome" id="welcome" rows="5" class="span3"><?php echo $this->row['welcome'];?></textarea>
                            <span class="help-inline" id="help-welcome"></span> </div>
                        </div>
                        
                        <div class="control-group" id="group-nodata">
                          <label class="control-label" for="nodata">搜索缺省提示</label>
                          <div class="controls">
                            <textarea name="nodata" id="nodata" rows="5" class="span3"><?php echo $this->row['nodata'];?></textarea>
                            <span class="help-inline" id="help-nodata"></span> </div>
                        </div>
					</div>
					<?php 
					}
					?>

				</div>

			</div>

		<?php echo $this->partial('partials/homeFooter.phtml');?>
</form>
	</div>
</div>
<script type="text/javascript">
        function parent(pid)
        {
        	$.post("/type/areas?pid="+pid,{},function(data){
                $('#area').html(data);
            	});
        }
</script> 