<div class="header">
  <h1 class="page-title">编辑账号</h1>
</div>
<ul class="breadcrumb">
  <li><a href="/home">首页</a> <span class="divider">/</span></li>
  <li><a href="/users">用户列表</a> <span class="divider">/</span></li>
  <li class="active">编辑账号</li>
</ul>
<div class="container-fluid">
  <div class="row-fluid">
  <?php 
	if ($this->success)
	{
		echo "<div class=\"alert alert-success\">
        <a class=\"close\" data-dismiss=\"alert\">×</a>
        <strong>{$this->success->title}</strong>  {$this->success->message}</div>";
	}
	?>
    <form id="tab" name="editUser" method="post" action="?id=<?php echo $this->row['id'];?>" enctype="multipart/form-data">
      <div class="btn-toolbar">
        <input type="submit" name="submit" id="submit"  class="btn btn-primary" value="提交" />
        <div class="btn-group"></div>
      </div>
      <div class="well">
        <ul class="nav nav-tabs">
          <li class="active"><a href="#home" data-toggle="tab">基础配置</a></li>
          <li><a href="#profile" data-toggle="tab">密码设置</a></li>
        </ul>
        <div id="myTabContent" class="tab-content">
       <div class="tab-pane active in" id="home">
            <?php 
            if ($this->user->power==3)
            {
            ?>
            <div class="control-group" id="group-power">
              <label class="control-label" for="power">审核</label>
              <div class="controls">
                通过  <input type="radio" name="power" id="power_2" value="2" <?php echo $this->row['power']==2?'checked="checked"':'';?> > 
               待审核 <input type="radio" name="power" id="power_0" value="0" <?php echo $this->row['power']==0?'checked="checked"':'';?>>
                <span class="help-inline" id="help-power"></span> </div>
            </div>
		<?php 
            }
		  if ($this->user->power >=2 && $this->user->id != $this->row['id'])
		  {
		  ?>
            <div class="control-group" id="group-username">
              <label class="control-label" for="username">账号</label>
              <div class="controls">
                <input type="text" value="<?php echo $this->row['username'];?>" name="username" id="username" class="span3">
                <span class="help-inline" id="help-username"></span> </div>
            </div>
          <?php 
		  }
		  ?>
            <div class="control-group" id="group-realname">
              <label class="control-label" for="realname">姓名</label>
              <div class="controls">
                <input type="text" value="<?php echo $this->row['realname'];?>" name="realname" id="realname" class="span3">
                <span class="help-inline" id="help-realname"></span> </div>
            </div>
            <div class="control-group" id="group-email">
              <label class="control-label" for="email">邮箱</label>
              <div class="controls">
                <input type="text" value="<?php echo $this->row['email'];?>" name="email" id="email" class="span3">
                <span class="help-inline" id="help-email"></span> </div>
            </div>
            <div class="control-group" id="group-tel">
              <label class="control-label" for="tel">电话</label>
              <div class="controls">
                <input type="text" value="<?php echo $this->row['tel'];?>" name="tel" id="tel" class="span3">
                <span class="help-inline" id="help-tel"></span> </div>
            </div>
             <?php 
              if ($this->user->power==3)
              {
              ?>
            <div class="control-group" id="group-shopCount">
              <label class="control-label" for="shopCount">门店数</label>
              <div class="controls">
                <input type="text" value="<?php echo $this->row['shopCount'];?>" name="shopCount" id="shopCount" class="span3" onkeyup="value=value.replace(/[^\d]/g,'')">
                <span class="help-inline" id="help-shopCount"></span> </div>
            </div>
            <?php 
              }else
              {
              	  if ($this->row['shopCount'])
              	  {
              	      echo '门店数: <b>'.$this->row['shopCount'].'</b> 门店 <br /><br />';
              	  }
              }
              if ($this->row['power']==2)
              {
              	echo "
               <div class=\"control-group\" id=\"group-domain\">
                  <label class=\"control-label\" for=\"domain\"><b>URL：</b>".BASE_URL."/api/</label>
                </div>
                <div class=\"control-group\" id=\"group-token\">
                  <label class=\"control-label\" for=\"token\"><b>Token：</b>{$this->row['token']}</label>
                </div>
               ";
              }
               ?> 
            </div>
          <div class="tab-pane fade" id="profile">
            <div class="control-group" id="group-password">
              <label class="control-label" for="password">密码</label>
              <div class="controls">
                <input type="password" name="password" id="password" class="span3">
                <span class="help-inline" id="help-password"></span> </div>
            </div>
            <div class="control-group" id="group-repassword">
              <label class="control-label" for="repassword">确认密码</label>
              <div class="controls">
                <input type="password" name="repassword" id="repassword"
									class="span3">
                <span class="help-inline" id="help-repassword"></span> </div>
            </div>
          </div>
        </div>
      </div>
      <script type="text/javascript">
        function parent(pid)
        {
        	$.post("/type/areas?pid="+pid,{},function(data){
                $('#area').html(data);
            	});
        }
        </script> 
      <?php echo $this->partial('partials/homeFooter.phtml');?>
    </form>
  </div>
</div>
