<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>VIP客户登记</title>
<meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="">
<meta name="author" content="">
<link rel="stylesheet" type="text/css" href="/lib/bootstrap/css/bootstrap.css">
<link rel="stylesheet" type="text/css" href="/css/theme.css">
<link rel="stylesheet" href="/lib/font-awesome/css/font-awesome.css">
<script src="/lib/jquery-1.7.2.min.js" type="text/javascript"></script>

<!-- Demo page code -->

<style type="text/css">
#line-chart {
	height: 300px;
	width: 800px;
	margin: 0px auto;
	margin-top: 1em;
}

.brand {
	font-family: georgia, serif;
}

.brand .first {
	color: #ccc;
	font-style: italic;
}

.brand .second {
	color: #fff;
	font-weight: bold;
}
</style>

<!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
<!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
</head>

<!--[if lt IE 7 ]> <body class="ie ie6"> <![endif]-->
<!--[if IE 7 ]> <body class="ie ie7 "> <![endif]-->
<!--[if IE 8 ]> <body class="ie ie8 "> <![endif]-->
<!--[if IE 9 ]> <body class="ie ie9 "> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!-->
<body class="">
	<!--<![endif]-->

	<div class="navbar">
		<div class="navbar-inner">
			<ul class="nav pull-right">
			</ul>
			<a class="brand"><!-- <span class="first">Your</span> -->
				<span class="second">VIP客户登记</span></a>
		</div>
	</div>
	<div class="row-fluid">
		<div class="dialog">
		<?php 
		if ($this->error)
		{
			echo "<div class=\"alert alert-error\"><a class=\"close\" data-dismiss=\"alert\">×</a><strong>{$this->error->title}:</strong> {$this->error->message} </div>";
		}
    	if ($this->success)
    	{
    		echo "<div class=\"alert alert-success\">
            <a class=\"close\" data-dismiss=\"alert\">×</a>
            <strong>{$this->success->title}</strong>  {$this->success->message}</div>";
    	}
    	?>
			<div class="block">
				<p class="block-heading">VIP客户登记(均为必填项)</p>
				<div class="block-body">
					<form method="post" action="?time=<?php echo time();?>" onSubmit="return clickForm();">
					    <div class="control-group" id="group-realname">
                            <label class="control-label" for="realname">公司名称</label>
                            <div class="controls">
                              <input type="text" name="realname" id="realname" placeholder="请输入公司名称" class="span8">
                              <span class="help-inline" id="help-realname"></span>
                            </div>
                        </div>
                        <div class="control-group" id="group-email">
                            <label class="control-label" for="email">邮 箱</label>
                            <div class="controls">
                              <input type="text" name="email" id="email" placeholder="请输入邮箱" class="span8">
                              <span class="help-inline" id="help-email"></span>
                            </div>
                        </div>
                        <div class="control-group" id="group-tel">
                            <label class="control-label" for="tel">电 话(固话或手机)</label>
                            <div class="controls">
                              <input type="text" name="tel" id="tel" placeholder="请输入电话" class="span8">
                              <span class="help-inline" id="help-tel"></span>
                            </div>
                        </div>
                        <div class="control-group" id="group-username">
                            <label class="control-label" for="username">用户名</label>
                            <div class="controls">
                              <input type="text" name="username" id="username" placeholder="请输入用户名" class="span8">
                              <span class="help-inline" id="help-username"></span>
                            </div>
                        </div>
                        <div class="control-group" id="group-password">
                            <label class="control-label" for="password">密   码</label>
                            <div class="controls">
                              <input type="password" name="password" id="password" placeholder="请输入密码" class="span8">
                              <span class="help-inline" id="help-password"></span>
                            </div>
                        </div>
                        <div class="control-group" id="group-repassword">
                            <label class="control-label" for="repassword">密   码</label>
                            <div class="controls">
                              <input type="password" name="repassword" id="repassword" placeholder="请再次确认密码" class="span8">
                              <span class="help-inline" id="help-repassword"></span>
                            </div>
                        </div>
						<label class="remember-me"><b>注意：</b>请在登记完成稍后，我们将进行审核确认，审核通过，我们将在系统配置完毕之后通知您使用！</label>
						<input type="submit" name="submit" value="现在登记" class="btn btn-primary pull-right"> 
						<label class="remember-me"><input name="isok" type="checkbox" id="isok" value="1" checked>
			        是否同意 注册条款</label>
			        
						<div class="clearfix"></div>
					</form>
				</div>
			</div>
		</div>
	</div>
	<script src="/lib/bootstrap/js/bootstrap.js"></script>
    <script src="/lib/signup.js"></script>
</body>
</html>


