<!DOCTYPE HTML>
<html lang="zh-CN">
<head>
	<meta charset="utf-8" />
	<title>联系我们</title>
	<meta name="version" content="游太网络" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0;" />
	<meta name="format-detection" content="telephone=no" />
	<link type="text/css" rel="stylesheet" href="/css/style.css" />
	<script type="text/javascript" src="/js/jquery.min.js"></script>
	<script type="text/javascript" src="/js/main.js"></script>
</head>

<body>
	<?php echo $this->partial ( 'partials/header.phtml',array('openid'=>$this->openid));?>
	<!--主体-->
<div class="main">
	<div class="o_success">
		<h1>联系我们</h1>
		<ul>
            <li>
            	<p>联系我们...</p>
            	<p>联系我们...</p>
            	<p>联系我们...</p>
           	</li>
		</ul>
	</div>
</div>
<?php echo $this->partial ( 'partials/footer.phtml',array('openid'=>$this->openid));?>
</body>
</html>