<!DOCTYPE HTML>
<html lang="zh-CN">
<head>
<meta charset="utf-8" />
<title>出错啦</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0;" />
<meta name="format-detection" content="telephone=no" />
<link type="text/css" rel="stylesheet" href="/css/style.css" />
<script type="text/javascript" src="/js/jquery.min.js"></script>
</head>

<body>
<!--头部-->
<header class="ts1">
	<a class="u_back fl" href="/?openid=<?php echo $this->openid;?>">首页</a>
</header>
<!--主体-->
<div class="u_main">
	<div class="none_order ts2">
        <img src="/images/u_sad.jpg" width="77" height="77" alt="sad face" />
        <h2><p>不正确的用户信息，请重新从微信端登录！</p></h2>
        <p>&nbsp;</p>
        <p>&nbsp;</p>
    </div>
</div>
<!--底部-->
<?php echo $this->partial ( 'partials/footer.phtml');?>
</body>
</html>