<div class="header">
	<h1 class="page-title">有问必答</h1>
</div>

<ul class="breadcrumb">
	<li><a href="/home">首页</a> <span class="divider">/</span></li>
	<li><a href="/answers">有问必答</a> <span class="divider">/</span></li>
	<li class="active">回答问题</li>
</ul>

<div class="container-fluid">
	<div class="row-fluid">
	    <?php 
    	if ($this->success)
    	{
    		echo "<div class=\"alert alert-success\">
            <a class=\"close\" data-dismiss=\"alert\">×</a>
            <strong>{$this->success->title}</strong>  {$this->success->message}</div>";
    	}
    	?>
		<form id="tab" name="answer" method="post" action="?id=<?php echo $this->row['id'];?>">
			<div class="btn-toolbar">
				<input type="submit" name="submit" id="submit"
					class="btn btn-primary " value="提交" />
				<div class="btn-group"></div>
			</div>
			<div class="well">
				<!-- <ul class="nav nav-tabs">
					<li class="active"><a href="#home" data-toggle="tab">提交问题</a></li>
				</ul> -->

				<div id="myTabContent" class="tab-content">
					<div class="tab-pane active in" id="home">
						<div class="control-group" id="group-realname">
							<label class="control-label" for="realname"><b>联系人：</b><?php echo $this->row['realname'];?></label>
						</div>
						<div class="control-group" id="group-contact">
							<label class="control-label" for="contact"><b>电&nbsp;&nbsp;&nbsp;话：</b><?php echo $this->row['contact'];?></label>
						</div>
						<div class="control-group" id="group-ask">
							<label class="control-label" for="ask"><b>问&nbsp;&nbsp;&nbsp;题：</b></label>
							<div class="controls">
								<?php echo htmlspecialchars_decode(stripcslashes($this->row['ask']));?>
								<span class="help-inline" id="help-contact"></span>
							</div>
						</div>
						<div class="control-group" id="group-contact">
							<label class="control-label" for="contact"><b>回&nbsp;&nbsp;&nbsp;答：</b></label>
							<div class="controls">
								<textarea rows="5" name="answer" id="answer" class="span8"><?php echo htmlspecialchars_decode(stripcslashes($this->row['answer']));?></textarea>
								<span class="help-inline" id="help-contact"></span>
							</div>
						</div>
					</div>
				</div>
			</div>
		<?php echo $this->partial('partials/homeFooter.phtml');?>
</form>
	</div>
</div>
