<div class="header">
	<h1 class="page-title">有问必答</h1>
</div>

<ul class="breadcrumb">
	<li><a href="/home">首页</a> <span class="divider">/</span></li>
	<li><a href="/answers">有问必答</a> <span class="divider">/</span></li>
	<li class="active">提交问题</li>
</ul>

<div class="container-fluid">
	<div class="row-fluid">
	    <?php 
    	if ($this->success)
    	{
    		echo "<div class=\"alert alert-success\">
            <a class=\"close\" data-dismiss=\"alert\">×</a>
            <strong>{$this->success->title}</strong>  {$this->success->message}</div>";
    	}
    	?>
		<form id="tab" name="createAnswers" method="post" action="" onsubmit="return clickForm();">
			<div class="btn-toolbar">
				<input type="submit" name="submit" id="submit"
					class="btn btn-primary " value="提交" />
				<div class="btn-group"></div>
			</div>
			<div class="well">
				<div id="myTabContent" class="tab-content">
					<div class="tab-pane active in" id="home">
						<div class="control-group" id="group-realname">
							<label class="control-label" for="realname">联系人</label>
							<div class="controls">
								<input type="text" value="" name="realname" id="realname" class="span3"> 
								<span class="help-inline" id="help-realname"></span>
							</div>
						</div>
						<div class="control-group" id="group-contact">
							<label class="control-label" for="contact">联系方式</label>
							<div class="controls">
								<input type="text" value="" name="contact" id="contact" class="span3"> 
								<span class="help-inline" id="help-contact"></span>
							</div>
						</div>
						<div class="control-group" id="group-ask">
							<label class="control-label" for="ask">问题</label>
							<div class="controls">
								<textarea rows="5" name="ask" id="ask" class="span8"></textarea>
								<span class="help-inline" id="help-ask"></span>
							</div>
						</div>
					</div>
				</div>
			</div>
		<?php echo $this->partial('partials/homeFooter.phtml');?>
</form>
	</div>
</div>