<div class="header">
	<h1 class="page-title">问题列表</h1>
</div>

<ul class="breadcrumb">
	<li><a href="/home">首页</a> <span class="divider">/</span></li>
	<li class="active">问题列表</li>
</ul>

<div class="container-fluid">
	<div class="row-fluid">
	<?php 
	if ($this->success)
	{
	    echo "<div class=\"alert alert-success\">
        <a class=\"close\" data-dismiss=\"alert\">×</a>
        <strong>{$this->success->title}</strong>  {$this->success->message}</div>";
	}
	?>
		<div class="btn-toolbar">
			<a href="/answers/create" class="btn btn-primary"><i class="icon-plus"></i> 我有问题</a>
			<div class="btn-group"></div>
		</div>
		<div class="well">
			<table class="table">
				<thead>
					<tr>
						<th width="6%">#</th>
						<th>提问内容</th>
						<th width="120px;">提问时间</th>
						<th width="80px;">是否回复</th>
						<?php echo $this->user->power==3?'<th width="50px;">回复</th>':'';?>
					</tr>
				</thead>
				<tbody>
				<?php 
				if ($this->rows)
				{
				    foreach ($this->rows as $val) {
				?>
					<tr>
						<td><?php echo $val['id'];?></td>
						<td><a href="/answers/view?id=<?php echo $val['id'];?>"><?php echo $val['ask'];?></a></td>
						<td><?php echo date('Y-m-d',$val['askTime']);?></td>
						<td><?php echo $val['answerTime']?'已回复':'未回复';?></td>
						<?php echo $this->user->power==3?"<td><a href=\"/answers/answer?id={$val['id']}\">回复</a></td>":'';?>
					</tr>
				<?php
				     } 
				}
				?>	
				</tbody>
			</table>
		</div>
		<?php 
		echo $this->paginationcontrol($this->rows,'Sliding','pagination/pagination.phtml');
		?>
		<?php 
		echo $this->partial('partials/homeFooter.phtml');
		?>
	</div>
</div>