<div class="header">
	<h1 class="page-title">有问必答</h1>
</div>

<ul class="breadcrumb">
	<li><a href="/home">首页</a> <span class="divider">/</span></li>
	<li><a href="/answers">有问必答</a> <span class="divider">/</span></li>
	<li class="active">回答问题</li>
</ul>

<div class="container-fluid">
	<div class="row-fluid">
			<div class="well">
				<!-- <ul class="nav nav-tabs">
					<li class="active"><a href="#home" data-toggle="tab">提交问题</a></li>
				</ul> -->

				<div id="myTabContent" class="tab-content">
					<div class="tab-pane active in" id="home">
						<div class="control-group" id="group-realname">
							<label class="control-label" for="realname"><b>联系人：</b><?php echo $this->row['realname'];?></label>
						</div>
						<div class="control-group" id="group-contact">
							<label class="control-label" for="contact"><b>电话：</b><?php echo $this->row['contact'];?></label>
						</div>
						<div class="control-group" id="group-ask">
							<label class="control-label" for="ask"><b>问题：</b></label>
							<div class="controls">
								<?php echo htmlspecialchars_decode(stripcslashes($this->row['ask']));?>
								<span class="help-inline" id="help-contact"></span>
							</div>
						</div>
						<div class="control-group" id="group-contact" style="color: orange">
							<label class="control-label" for="contact"><b>回答：</b></label>
							<div class="controls">
								<?php echo htmlspecialchars_decode(stripcslashes($this->row['answer']));?>
								<span class="help-inline" id="help-contact"></span>
							</div>
						</div>
					</div>
				</div>
			</div>
		<?php echo $this->partial('partials/homeFooter.phtml');?>
	</div>
</div>
