<?php 
if ($this->pageCount):
?>
<div class="pagination">
			<ul>
			<!-- Previous page link -->
			<li><a href="javascript:void(0);">总共 <?php echo $this->totalItemCount;?> 条数据，每页 <?php echo $this->itemCountPerPage;?> 条 ,当前页 <?php echo $this->currentItemCount;?> 条；共<?php echo $this->pageCount;?> 页,当前第 <?php echo $this->current;?> 页</a></li>
			<?php if (isset($this->previous)): ?>
            <li><a href="
            <?php 
            echo $this->url($this->route, array('action' => 'index','page'=>$this->previous));
            //门店管理员
            echo $this->action=='m'?"?action={$this->action}&id={$this->id}":'';
            //设置商品欢迎推荐
            echo $this->action=='c'?"?action={$this->action}":'';
            ?>
            ">前一页</a></li>
            <?php else: ?>
            <li><a href="">前一页</a></li>
            <?php endif; ?>
            <!-- Numbered page links -->
            <?php foreach ($this->pagesInRange as $page): ?>
            <?php if ($page != $this->current): ?>
            <li><a href="
            <?php 
            echo $this->url($this->route, array('action' => 'index','page'=>$page));
            //门店管理员
            echo $this->action=='m'?"?action={$this->action}&id={$this->id}":'';
            //设置商品欢迎推荐
            echo $this->action=='c'?"?action={$this->action}":'';
            ?>
            "><?php echo $page; ?></a></li>
            <?php else: ?>
            <li><a href=""><?php echo $page; ?></a></li>
            <?php endif; ?>
            <?php endforeach; ?>
            <!-- Next page link -->
            <?php if (isset($this->next)): ?>
            <li><a href="
            <?php 
            echo $this->url($this->route, array('action' => 'index','page'=>$this->next));
            //门店管理员
            echo $this->action=='m'?"?action={$this->action}&id={$this->id}":'';
            //设置商品欢迎推荐
            echo $this->action=='c'?"?action={$this->action}":'';
            ?>
            ">下一页</a></li>
            <?php else: ?>
             <li><a href="">下一页</a></li>
             <?php endif; ?>
			</ul>
</div>
<?php 
endif;
?>