<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>SCRM系统登陆</title>
<meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="">
<meta name="author" content="">
<link rel="stylesheet" type="text/css"
	href="/lib/bootstrap/css/bootstrap.css">
<link rel="stylesheet" type="text/css" href="/css/theme.css">
<link rel="stylesheet" href="/lib/font-awesome/css/font-awesome.css">
<script src="/lib/jquery-1.7.2.min.js" type="text/javascript"></script>
<!-- Demo page code -->
<style type="text/css">
#line-chart {
	height: 300px;
	width: 800px;
	margin: 0px auto;
	margin-top: 1em;
}

.brand {
	font-family: georgia, serif;
}

.brand .first {
	color: #ccc;
	font-style: italic;
}

.brand .second {
	color: #fff;
	font-weight: bold;
}
</style>

<!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
<!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
</head>

<!--[if lt IE 7 ]> <body class="ie ie6"> <![endif]-->
<!--[if IE 7 ]> <body class="ie ie7 "> <![endif]-->
<!--[if IE 8 ]> <body class="ie ie8 "> <![endif]-->
<!--[if IE 9 ]> <body class="ie ie9 "> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!-->
<body class="">
	<!--<![endif]-->

	<div class="navbar">
		<div class="navbar-inner">
			<ul class="nav pull-right">

			</ul>
			<a class="brand" href="/"><!-- <span class="first">Your</span>  --><span class="second">SCRM系统登陆</span></a>
		</div>
	</div>
	<div class="row-fluid">
		<div class="dialog">
		<?php 
		if ($this->hint)
		{
		?>
		<div class="alert alert-error">
        <a class="close" data-dismiss="alert">×</a>
        <strong><?php echo $this->hint['title'];?>:</strong> <?php echo $this->hint['message'];?></div>
        <?php 
		}
        ?>
			<div class="block">
				<p class="block-heading">登陆</p>
				<div class="block-body">
					<form method="post" action="">
						<label>账号</label> <input type="text" name="username"
							class="span12"> <label>密码</label> <input type="password"
							name="password" class="span12">
							<div style="float:right"> 
							<input type="submit" name="submit" value="提交" class="btn btn-primary"> 
							<input type="reset" class="btn" name="reset" value="重置">
							</div>
						<div class="clearfix"></div>
					</form>
				</div>
			</div>
			<!-- <p class="pull-right" style="">
				<a href="/users/signup">注册</a>
			</p>
			<p>
				<a href="">找回密码</a>
			</p> -->
		</div>
	</div>
	<script src="/lib/bootstrap/js/bootstrap.js"></script>
	<script type="text/javascript">
        $("[rel=tooltip]").tooltip();
        $(function() {
            $('.demo-cancel-click').click(function(){return false;});
        });
    </script>
</body>
</html>


